<<<<<<< HEAD
theme: jekyll-theme-minimal
title: 'Language in Peace and Conflict Studies'
=======
theme: jekyll-theme-cayman
title: 'Language in Peacebuilding'
>>>>>>> 69345fb349c629469d3e5d453df996f6eab12a0e
